// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIh01USae_-tkptC9OOxurDL_pZmAta50',
    appId: '1:522968736205:web:ddd406dcf5be69cebc2484',
    messagingSenderId: '522968736205',
    projectId: 'calvin-chess-trainer',
    authDomain: 'calvin-chess-trainer.firebaseapp.com',
    storageBucket: 'calvin-chess-trainer.firebasestorage.app',
    measurementId: 'G-LZK9E0VDNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKfuRrhOmubtUEiqfo2NeutWEdmCHLzis',
    appId: '1:522968736205:android:c103c5a3903aaa35bc2484',
    messagingSenderId: '522968736205',
    projectId: 'calvin-chess-trainer',
    storageBucket: 'calvin-chess-trainer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIC53Bl8Swz3vwYlzUEixRikWZxEjXpMg',
    appId: '1:522968736205:ios:22715df195c09ba4bc2484',
    messagingSenderId: '522968736205',
    projectId: 'calvin-chess-trainer',
    storageBucket: 'calvin-chess-trainer.firebasestorage.app',
    iosBundleId: 'education.internut.calvinchesstrainer.dev',
  );
}
